name: SonarQube Quality Gate Check

on:
  push:
    branches:
      - "*" # Set the branch you want to trigger this workflow on
  pull_request:
    branches:
      - "*" # Set the branch you want to trigger this workflow on

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: "11"

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and analyze with SonarQube
        run: |
          mvn clean install sonar:sonar \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_LOGIN_TOKEN }} \
            -Dsonar.projectKey=${{ secrets.PROJECT_KEY }}
        env:
          SONARQUBE_SERVER_URL: ${{ secrets.SONAR_HOST_URL }}
          SONARQUBE_AUTH_TOKEN: ${{ secrets.SONAR_LOGIN_TOKEN }}

      - name: Check SonarQube Quality Gate status
        run: |
          STATUS=$(curl -s "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=${{ secrets.PROJECT_KEY }}" \
                    -u "${{ secrets.SONAR_TOKEN }}" | jq -r .projectStatus.status)
          echo "SonarQube Quality Gate status: $STATUS"
          if [ "$STATUS" != "OK" ]; then
            echo "SonarQube Quality Gate Failed !!"
          exit 1
          else
            echo "SonarQube Quality Gate passed !!" 
          fi